#!/bin/sh 

set -e

case "$1" in
	remove|deconfigure)
		/etc/init.d/freedwall stop
		update-rc.d -f freedwall remove
		;;
	upgrade)
		;;
	failed-upgrade)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 0
		;;
esac


exit 0
